"""table update check

Revision ID: 32f975fc7bbc
Revises: e99b4819a40e
Create Date: 2024-01-08 13:47:31.815410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f975fc7bbc'
down_revision: Union[str, None] = 'e99b4819a40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tableisis', sa.Column('messagesssss', sa.Integer(), nullable=True))
    op.drop_column('tableisis', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tableisis', sa.Column('message', sa.INTEGER(), nullable=True))
    op.drop_column('tableisis', 'messagesssss')
    # ### end Alembic commands ###
