"""Initial migrationaasdasdasd

Revision ID: 79ba244914b9
Revises: 0fb9510bd209
Create Date: 2024-01-06 20:51:56.149724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ba244914b9'
down_revision: Union[str, None] = '0fb9510bd209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asdnower', sa.Column('emailsing', sa.Integer(), nullable=True))
    op.drop_column('asdnower', 'emailing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asdnower', sa.Column('emailing', sa.INTEGER(), nullable=True))
    op.drop_column('asdnower', 'emailsing')
    # ### end Alembic commands ###
