"""testing table creation in different file

Revision ID: 9d2baceb1945
Revises: 2e05e7ee20b6
Create Date: 2024-01-07 14:42:40.065818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2baceb1945'
down_revision: Union[str, None] = '2e05e7ee20b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
