"""Add Admin ID to group model 4

Revision ID: aca3cc5f899b
Revises: e0b052cd2a99
Create Date: 2024-02-17 00:32:21.013289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca3cc5f899b'
down_revision: Union[str, None] = 'e0b052cd2a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
