"""Add Admin ID to group model 2

Revision ID: efe857218e3e
Revises: 2ac660a4dcac
Create Date: 2024-02-17 00:19:46.285627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe857218e3e'
down_revision: Union[str, None] = '2ac660a4dcac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
